### ISSUE TITLE
error C2733: “_mm_xor_pd”: you cannot overload a function with 'C' linkage

### ISSUE THREAD

**Issue by damnkk** [NVIDIA-RTX/NRIFramework#5] opened 2024-07-28 12:27 UTC
I met a series fatal error after I udpate the NRIFramework(from the commit 98786ec96fd  to the latest) ,It looks like all these functions are declared in "MathLib".
So, may I get some advice to clear these error?Any help is greatly appreciated, thank you for your time:-)
![image](https://github.com/user-attachments/assets/f41522c5-2bff-436a-940b-bd28f882e8c0)
following is the original building log
*******************************************************************************************************************
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(509): error C2061: 语法错误: 标识符“_mm_and_pd”
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(509): error C2733: “_mm_xor_pd”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\emmintrin.h(101): note: 参见“_mm_xor_pd”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(510): error C2061: 语法错误: 标识符“_mm_and_ps”
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(510): error C2733: “_mm_xor_ps”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\xmmintrin.h(233): note: 参见“_mm_xor_ps”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(512): error C2061: 语法错误: 标识符“_mm_and_pd”
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(512): error C2733: “_mm_xor_pd”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\emmintrin.h(101): note: 参见“_mm_xor_pd”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(513): error C2061: 语法错误: 标识符“_mm_and_ps”
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(513): error C2733: “_mm_xor_ps”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\xmmintrin.h(233): note: 参见“_mm_xor_ps”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(664): error C2768: “emu_mm_dp_ps”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(721): error C2768: “emu_mm_max_epx”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(724): error C2768: “emu_mm_max_epx”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(724): error C2733: “emu_mm_max_epx”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(721): note: 参见“emu_mm_max_epx”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(732): error C2768: “emu_mm_min_epx”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(735): error C2768: “emu_mm_min_epx”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(735): error C2733: “emu_mm_min_epx”: 无法重载具有外部 "C" 链接的函数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(732): note: 参见“emu_mm_min_epx”的声明
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(783): error C2768: “emu_mm_round_pd”: 非法使用显式模板参数
[build] C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\include\intrin.h(784): error C2768: “emu_mm_round_ps”: 非法使用显式模板参数

**Comment by dzhdanNV** [comment] 2024-07-29 08:53
`_mm_xor_pd` (and others from your log) is a basic SSE2 intrinsic, which is always available on Windows and doesn't require emulation. Projects, using ML, do definitely compile on Windows using VS2022 and Linux. Are you sure that `_mm_xor_pd` is not coming from `sse2neon.h`? There is a bunch of includes in `Macro stuff` section. Please, could you share the include files, you are getting, in order of appearance? I can't understand where is overloading taking place?

**Comment by damnkk** [comment] 2024-08-01 03:47
here is my project, a very simple rt renderer, almost modify from 'NRISample/raytracingbox'. The latest change is in "develop" branch(and only can launch on win64, with vulkan backend).
[https://github.com/damnkk/MTX/tree/develop](url)
******************************************************
I do know that some header files need to adhere to a certain include order，like"Extensions/NRIRayTracing.h"must be included after the "NRIFramework.h". But after I checked these points, I still couldn't avoid the problem.
******************************************************
If you are willing to spend a small amount of time to check it for me, I will be very grateful. It will help me learn more deeply. 
^_^

**Comment by dzhdanNV** [comment] 2024-08-01 04:35
I clicked on the link, but got `No results matched your search` :( Is it a private repo?

**Comment by dzhdanNV** [comment] 2024-08-01 05:03
Ha-ha. The text is OK, but the link is not. Looking...

**Comment by damnkk** [comment] 2024-08-01 05:17
I hardcoded 2 resource paths in renderer.cpp **Initialize()** function(Hope this doesn't bother you），thanks again

**Comment by dzhdanNV** [comment] 2024-08-01 05:46
The problem is in overengineered projected called `spdlog`. It includes intrinsic related headers and even Windows related stuff. If I comment this in your `Log.h`:
```c++
//#include <spdlog/spdlog.h>

#define MTX_INFO(format, ...)//  spdlog::info(format, ##__VA_ARGS__);
#define MTX_WARN(format, ...)//  spdlog::warn(format, ##__VA_ARGS__);
#define MTX_ERROR(format, ...)// spdlog::error(format, ##__VA_ARGS__);
#define MTX_ASSERT(condition)                                                                      \
  if (!(condition)) {                                                                              \
    /*spdlog::error("Assert fail in File::{}->Line::{}", __FILE__, __LINE__);*/                    \
    exit(-1);                                                                                      \
  }

#define MTX_CHECK(res) MTX_ASSERT(res == nri::Result::SUCCESS)
```
MTX compiles. Modern ML brings new restrictions, but most of them are hard / impossible to address. The top of `ml.h` includes these guidelines:
```c++
/*
IMPORTANT:
- intrinsic related headers must not be included *AFTER* ML inclusion
- if "cstdlib" and "cmath" are included explicitly or implicitly, they must be included *BEFORE* ML
- "ML_NAMESPACE" macro can be defined to put the entire ML into "ml" namespace
*/
```
In your case `spdlog.h` gets included AFTER `ml.h`.

**Comment by dzhdanNV** [comment] 2024-08-01 06:09
Closing?

**Comment by damnkk** [comment] 2024-08-01 06:09
Thank U for ur time, I will fix this issue!! 🫡

**Closed as completed** 2024-08-01 06:09 UTC
